apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-site-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # ✅ debe coincidir con el PV
