apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-site-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/mnt/web"
  persistentVolumeReclaimPolicy: Retain
