apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-site-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # ✅ obligatorio para que el PVC lo reconozca
  hostPath:
    path: "/mnt/web"
